"""Run the confirmatory hold-out evaluation and write reports/holdout_results.md."""

from __future__ import annotations

import json
from datetime import datetime, timezone

import pandas as pd

from marginalis.analysis import exclusions as ex
from marginalis.analysis import holdout as ho
from marginalis.analysis.data import read_fuel_mix, read_mef_profile, read_split, read_view
from marginalis.analysis.findings import OVERNIGHT, _md, pooled_estimate, window_comparison
from marginalis.config import BAS, HOLDOUT, HOLDOUT_YTD, METHOD_FROZEN, REPORTS_DIR

SOURCES = ("eia", "derived")
BA_ORDER = ["ERCO", "CISO", "MISO"]


def verdict(predicted: float, lo: float, hi: float) -> str:
    if predicted > hi:
        return "overstated"
    if predicted < lo:
        return "understated"
    return "held"


def evaluate_period(split, prof_all: pd.DataFrame, gas_rule: bool = True) -> dict:
    """gas_rule=False is a disclosed, non-confirmatory sensitivity only."""
    h, d, f = read_split("hour", split), read_split("delta", split), read_split("fuel", split)
    bad_days = ex.gas_as_other_days(f, h)
    if not gas_rule:
        bad_days = bad_days.iloc[0:0]
    h_bad, d_bad = ex.on_days(h, bad_days), ex.on_days(d, bad_days)
    rows, sens, pred_rows, overnight = [], [], [], []
    for ba in BA_ORDER:
        tz = BAS[ba].timezone
        hb, dbm = h["ba_code"] == ba, d["ba_code"] == ba
        for src in SOURCES:
            prof = prof_all[(prof_all["ba_code"] == ba) & (prof_all["spec"] == "demand")
                            & (prof_all["emissions_source"] == src)]
            slopes = ho.holdout_slopes(d[dbm], d_bad[dbm], src, f"{split.name}|{ba}|{src}")
            for w in (ho.W_PRIMARY, *ho.W_SENSITIVITY):
                win = ho.daily_windows(h[hb], prof, tz, w)
                wts = ho.stratum_weights(h[hb], win, w)
                g = ho.gap(wts, slopes, prof) if len(wts) else {
                    "realised": 0.0, "ci_low": 0.0, "ci_high": 0.0, "predicted": 0.0, "min_stratum_n": 0,
                    "dropped_replicates_pct": 0.0}
                rec = {"BA": ba, "source": src, "W": w, "days": len(win),
                       "days windows differ": int((win["start_m"] != win["start_a"]).sum()), **g}
                if w == ho.W_PRIMARY:
                    rec["avg intensity, marginal windows"] = ho.realised_avg_intensity(
                        h[hb], h_bad[hb], src, ho.window_hours(win, "m"))
                    rec["avg intensity, average windows"] = ho.realised_avg_intensity(
                        h[hb], h_bad[hb], src, ho.window_hours(win, "a"))
                    rows.append(rec)
                else:
                    sens.append(rec)
            pred_rows.append({"BA": ba, "source": src, **ho.predictive_check(d[dbm], d_bad[dbm], prof, src)})
    for i, src in enumerate(SOURCES):
        r = pooled_estimate(d, h, bad_days, "MISO", OVERNIGHT, src, 100 + i)
        overnight.append({"source": src, "MEF": r.mef, "CI low": r.ci_low, "CI high": r.ci_high,
                          "average": r.avg, "n": r.n_obs})
    return {"split": split, "bad_days": bad_days, "main": pd.DataFrame(rows), "sens": pd.DataFrame(sens),
            "pred": pd.DataFrame(pred_rows), "overnight": pd.DataFrame(overnight),
            "hours": int(len(h)), "range": (h["ts_utc"].min(), h["ts_utc"].max())}


def run() -> str:
    assert METHOD_FROZEN, "hold-out evaluation requires the frozen method"
    prof = read_mef_profile()
    eda_pred = window_comparison(prof).groupby(["BA", "source"])["predicted gap (kg/MWh)"].mean()
    res = [evaluate_period(HOLDOUT, prof), evaluate_period(HOLDOUT_YTD, prof)]
    fired = [r for r in res if len(r["bad_days"])]
    no_rule = {r["split"].name: evaluate_period(r["split"], prof, gas_rule=False) for r in fired}

    for r in res:
        m = r["main"]
        m["meets rule"] = (m["realised"] >= ho.THRESHOLD_KG) & (m["ci_low"] > 0)
        m["EDA predicted"] = [eda_pred[(b, s)] for b, s in zip(m["BA"], m["source"])]
        m["vs EDA"] = [verdict(p, lo, hi) for p, lo, hi in zip(m["EDA predicted"], m["ci_low"], m["ci_high"])]
        m["vs same-days prediction"] = [verdict(p, lo, hi) for p, lo, hi in zip(m["predicted"], m["ci_low"], m["ci_high"])]
        m["realised / EDA"] = m["realised"] / m["EDA predicted"]
    h1 = res[0]["main"]
    decision = h1.groupby("BA")["meets rule"].all().reindex(BA_ORDER)

    L = []
    add = L.append
    add("# Marginalis: pre-registered hold-out evaluation\n")
    add(f"_Generated by `marginalis evaluate` at {datetime.now(timezone.utc):%Y-%m-%d %H:%M} UTC. "
        "Confirmatory run: the method was frozen in commit `000f910` (`METHOD_FROZEN = True`), and "
        "`mef_profile`, the estimator and the exclusion rules were not changed. The evaluation procedure "
        "was fixed in `docs/preregistration.md` (Evaluation details) before the first hold-out read. "
        "This is that first read._\n")

    add("## Result\n")
    for ba in BA_ORDER:
        rr = h1[h1["BA"] == ba].set_index("source")
        add(f"- **{ba}:** realised gap {rr.loc['eia', 'realised']:,.0f} kg CO₂/MWh shifted "
            f"(95% CI {rr.loc['eia', 'ci_low']:,.0f} to {rr.loc['eia', 'ci_high']:,.0f}; derived "
            f"{rr.loc['derived', 'realised']:,.0f}, CI {rr.loc['derived', 'ci_low']:,.0f} to "
            f"{rr.loc['derived', 'ci_high']:,.0f}). The EDA predicted {rr.loc['eia', 'EDA predicted']:,.0f}. "
            f"Decision: average-based scheduling is **{'materially worse' if decision[ba] else 'not shown to be materially worse'}**.")
    add("")
    add("The decision rule (docs/preregistration.md) asks for a realised gap ≥ 50 kg CO₂ per MWh shifted "
        "with a 95% CI excluding zero, for **both** emissions sources in Hold-out 1 (2025).\n")

    e = h1[h1["source"] == "eia"].set_index("BA")
    h2 = res[1]["main"]
    e2 = h2[h2["source"] == "eia"].set_index("BA")
    add("### Did the EDA prediction hold?\n")
    add(f"The EDA predicted gaps of {e['EDA predicted'].min():,.0f}–{e['EDA predicted'].max():,.0f} kg/MWh (EIA). "
        f"Realised in 2025: {e['realised'].min():,.0f}–{e['realised'].max():,.0f}.\n")
    for ba in BA_ORDER:
        r1, r2 = e.loc[ba], e2.loc[ba]
        add(f"- **{ba}:** predicted {r1['EDA predicted']:,.0f}, realised {r1['realised']:,.0f} in 2025 "
            f"({r1['realised / EDA']:.2f}×, verdict *{r1['vs EDA']}*) and {r2['realised']:,.0f} in 2026 YTD "
            f"({r2['realised / EDA']:.2f}×, *{r2['vs EDA']}*)."
            + (" The prediction sits inside the CI, but the CI also includes zero, so the hold-out cannot "
               "separate the predicted effect from no effect: *held* here means *not contradicted*, not *confirmed*."
               if r1["vs EDA"] == "held" and r1["ci_low"] <= 0 else "")
            + (f" The EDA overstated the effect by {r1['EDA predicted'] - r1['realised']:,.0f} kg/MWh in 2025."
               if r1["vs EDA"] == "overstated" else "")
            + (" Confirmed: the realised gap clears the threshold in both hold-outs."
               if r1["meets rule"] and r2["meets rule"] else ""))
    add("")
    add("Overall, the winner's-curse warning in the EDA was right about CISO, where the predicted advantage "
        "mostly disappeared, and wrong about MISO, where the realised gap matched or exceeded the prediction.\n")
    p1 = res[0]["pred"].set_index(["BA", "source"])
    worse = [ba for ba in BA_ORDER if p1.loc[(ba, "eia"), "r2_marginal"] < p1.loc[(ba, "eia"), "r2_average"]]
    add("**Predictive check (hourly, 2025).** Out-of-sample R² of the marginal factors: "
        + ", ".join(f"{ba} {p1.loc[(ba, 'eia'), 'r2_marginal']:.2f}" for ba in BA_ORDER)
        + ". The average-intensity benchmark scores: "
        + ", ".join(f"{ba} {p1.loc[(ba, 'eia'), 'r2_average']:.2f}" for ba in BA_ORDER)
        + (f". The benchmark predicts hourly ΔCO₂ better in {' and '.join(worse)}. " if worse else ". ")
        + "Calibration slopes for the marginal factors are below 1 ("
        + ", ".join(f"{ba} {p1.loc[(ba, 'eia'), 'calib_marginal']:.2f}" for ba in BA_ORDER)
        + "), so the per-stratum estimates are too extreme hour by hour, as expected from ~165 observations "
          "per stratum. They are useful for ranking windows (the scheduler result) more than for predicting "
          "individual hours.\n")
    on = res[0]["overnight"].set_index("source")
    add(f"**MISO overnight.** 2025: marginal {on.loc['eia', 'MEF']:,.0f} kg/MWh (95% CI "
        f"{on.loc['eia', 'CI low']:,.0f}–{on.loc['eia', 'CI high']:,.0f}) vs average {on.loc['eia', 'average']:,.0f}. "
        f"Train was 732 (703–760) vs 459. The direction holds (marginal well above average), but the size shrank: "
        f"the gap is {on.loc['eia', 'MEF'] - on.loc['eia', 'average']:,.0f} kg/MWh against 273 in train, "
        "and the 2025 estimate lies below the train CI.\n")

    add("## Realised vs. predicted\n")
    add("The EDA's in-sample prediction was 78–213 kg/MWh (EIA; 82–212 derived), averaged over representative "
        "days for all 12 months. `same-days prediction` applies the training factors to exactly the hold-out "
        "days and windows used for the realised figure, so it isolates how much of any miss comes from the "
        "factors themselves rather than from the calendar. Verdict: **held** if the prediction lies inside "
        "the realised 95% CI, **overstated** if above it, **understated** if below it.\n")
    for r in res:
        m = r["main"]
        add(f"### {r['split'].name} ({r['range'][0] - pd.Timedelta(hours=1):%Y-%m-%d} → "
            f"{r['range'][1]:%Y-%m-%d}, {r['hours']:,} BA-hours)\n")
        t = m[["BA", "source", "days", "days windows differ", "EDA predicted", "predicted", "realised",
               "ci_low", "ci_high", "realised / EDA", "vs EDA", "vs same-days prediction", "meets rule",
               "min_stratum_n", "dropped_replicates_pct"]].rename(columns={
                   "predicted": "same-days prediction", "ci_low": "CI low", "ci_high": "CI high",
                   "min_stratum_n": "min stratum n", "dropped_replicates_pct": "dropped reps %"})
        add(_md(t, "{:,.2f}"))
        add("")
    add("`realised / EDA` below 1 means the EDA overstated the effect by that factor.\n")

    add("### What an average-based tool would have reported\n")
    add("Realised average intensity (Σ CO₂ / Σ net generation, hold-out) in each scheduler's chosen hours, "
        "Hold-out 1. The average scheduler wins on this metric by construction, which is the point: it "
        "measures the wrong thing for a scheduling decision.\n")
    add(_md(h1[["BA", "source", "avg intensity, marginal windows", "avg intensity, average windows"]]))
    add("")

    add("## MISO overnight check\n")
    add("The EDA recommendation: overnight (local 00:00–05:00) MISO hours looked cleanest on average (459 "
        "kg/MWh, train) but had a marginal factor of 732 kg/MWh (95% CI 703–760, EIA). Re-estimated on the "
        "hold-out with the same within-stratum pooled estimator:\n")
    for r in res:
        add(f"**{r['split'].name}**\n")
        add(_md(r["overnight"]))
        add("")
    add("## Predictive check\n")
    add("Out-of-sample fit of ΔCO₂ predicted as factor × Δdemand, per hold-out hour. The calibration slope "
        "is realised ΔCO₂ regressed on the prediction (1 = calibrated). The benchmark uses average intensity "
        "as the factor.\n")
    for r in res:
        add(f"**{r['split'].name}**\n")
        add(_md(r["pred"], "{:,.3f}"))
        add("")
    add("## Sensitivity: W = 2, 6, 8 hours (no decision)\n")
    for r in res:
        s = r["sens"].rename(columns={"ci_low": "CI low", "ci_high": "CI high", "predicted": "same-days prediction"})
        add(f"**{r['split'].name}**\n")
        add(_md(s[["BA", "source", "W", "days windows differ", "same-days prediction", "realised",
                   "CI low", "CI high"]], "{:,.1f}"))
        add("")
    add("## Exclusion rule on hold-out data\n")
    for r in res:
        bd = r["bad_days"]
        add(f"- {r['split'].name}: gas-as-Other rule fired on "
            + (", ".join(f"{b} {x:%Y-%m-%d}" for b, x in zip(bd["ba_code"], bd["local_date"])) if len(bd) else "no days")
            + (f" ({(bd['ba_code'] == 'CISO').sum()} CISO days)." if len(bd) else " (0 CISO days)."))
    add("")
    if no_rule:
        add("**The frozen rule produced false positives on CISO in 2026.** On these days CISO's gas output was "
            "already very low all day (≈600–950 MWh, 3–4% of generation), and batteries reported under 'Other' "
            "discharged 6–9 GW in the evening after charging at midday. So both thresholds were crossed by "
            "legitimate storage, not by gas being relabelled (the ERCO artifact is gas *collapsing* from ~25 GW "
            "into a flat ~22 GW of 'Other'). The rule was not changed, because the method is frozen, and the "
            "results above apply it as frozen. Hold-out 1, which carries the decision, is unaffected (the rule "
            "fired on no 2025 days). A future version should key on an abrupt gas-to-Other transfer rather "
            "than on levels.\n")
        add("Non-confirmatory sensitivity, same run without the gas-as-Other exclusion (W = 4 h):\n")
        for name, r in no_rule.items():
            m = r["main"]
            add(f"**{name}, rule off**\n")
            add(_md(m[["BA", "source", "predicted", "realised", "ci_low", "ci_high"]].rename(columns={
                "predicted": "same-days prediction", "ci_low": "CI low", "ci_high": "CI high"}), "{:,.1f}"))
            add("")
    add("## Notes\n")
    add("- Hold-out strata have one observation per day (≈30 per month × hour in a single year), so each "
        "hold-out slope is noisy. The realised gap averages many of them, and its CI reflects that.")
    add("- Bootstrap replicates that leave out every week of some stratum (possible with one year of data "
        "and 4–5 weeks per month) have an undefined slope and are dropped. Their share is the `dropped reps %` "
        "column. The resampling scheme itself is the pre-registered one, unchanged.")
    add("- Only complete local days are evaluated. Split boundaries are UTC, so each split begins and ends on "
        "a partial local day, where a scheduler cannot make the full daily choice.")
    add("- 'Realised' is estimated from hold-out data, because the marginal CO₂ of load that was not actually "
        "added cannot be observed directly. Same in-BA, demand-spec limitations as the EDA (no controls; "
        "imports not counted).")
    text = "\n".join(L)
    (REPORTS_DIR / "holdout_results.md").write_text(text, encoding="utf-8")
    write_json(res, no_rule, decision, eda_pred)
    return text


def _records(df: pd.DataFrame) -> list[dict]:
    return json.loads(df.to_json(orient="records", date_format="iso"))


def write_json(res, no_rule, decision, eda_pred) -> None:
    """Machine-readable results for the API (same numbers as the markdown report)."""
    h_tr, d_tr, f_tr = read_view("v_hour_train"), read_view("v_hour_delta_train"), read_fuel_mix()
    bad_tr = ex.gas_as_other_days(f_tr, h_tr)
    train_overnight = {}
    for i, src in enumerate(SOURCES):
        r = pooled_estimate(d_tr, h_tr, bad_tr, "MISO", OVERNIGHT, src, 1 + i)  # same seeds as the EDA
        train_overnight[src] = {"mef": r.mef, "ci_low": r.ci_low, "ci_high": r.ci_high, "average": r.avg, "n": r.n_obs}
    out = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "frozen_commit": "000f910",
        "threshold_kg_per_mwh": ho.THRESHOLD_KG,
        "primary_w": ho.W_PRIMARY,
        "overnight_local_hours": [min(OVERNIGHT), max(OVERNIGHT) + 1],
        "decision": {ba: bool(v) for ba, v in decision.items()},
        "eda_predicted_gap": {f"{b}|{s}": float(v) for (b, s), v in eda_pred.items()},
        "train_miso_overnight": train_overnight,
        "periods": {
            r["split"].name: {
                "start": r["split"].start.isoformat(), "end": r["split"].end.isoformat(),
                "main": _records(r["main"]), "sensitivity": _records(r["sens"]),
                "predictive": _records(r["pred"]), "miso_overnight": _records(r["overnight"]),
                "gas_as_other_days": _records(r["bad_days"]),
            } for r in res
        },
        "no_gas_rule_sensitivity": {name: _records(r["main"]) for name, r in no_rule.items()},
    }
    (REPORTS_DIR / "holdout_results.json").write_text(json.dumps(out, indent=2), encoding="utf-8")
